### ISSUE TITLE
Get returns nil when name of server is a number

### ISSUE THREAD

**Issue by mascheck** [hetznercloud/hcloud-go#128]
The clients try to parse the argument for `Get` as an integer. When the parsing succeeds it will interpret it as the id. When the server name for example is a number, it will not be found.

```go
 // Get retrieves a server by its ID if the input can be parsed as an integer, otherwise it
// retrieves a server by its name. If the server does not exist, nil is returned.
func (c *ServerClient) Get(ctx context.Context, idOrName string) (*Server, *Response, error) {
	if id, err := strconv.Atoi(idOrName); err == nil {
		return c.GetByID(ctx, int(id))
	}
	return c.GetByName(ctx, idOrName)
}
```

**Comment by thcyron** [comment]
The code does exactly what’s described in the documentation:

- If the input can be parsed as an integer, the input is interpreted as a server ID,
- otherwise (i.e. the input cannot be parsed as an integer) the input is interpreted as a server name.

Treating numeric inputs as server names in case there’s no server with that ID is a breaking change in my opinion. We must not change that before v2.

Personally, I would even remove that method in the next major version. The caller knows if the input is a ID or a name, we should not guess in the library.
