### ISSUE TITLE
Inconsistency in Load Balancer API

### ISSUE THREAD

**Issue by phm07** [hetznercloud/hcloud-go#520]
Currently, there are these methods to manage a Load Balancer's targets:
- `AddServerTarget`
- `AddIPTarget`
- `AddLabelSelectorTarget`
- `RemoveServerTarget`
- `RemoveIPTarget`
- `RemoveLabelSelectorTarget`

There are several problems/inconsistencies with these methods:
- For the `Add` methods, there are `Opts` structs, while for the `Remove` methods there are not.
- There is only a single API endpoint for adding/removing targets each (`POST /load_balancers/{id}/actions/add_target` and `POST /load_balancers/{id}/actions/remove_target`), so different methods for each type are not really needed
- This is harder to maintain and less straight forward

I propose two new methods `AddTarget` and `RemoveTarget`, which would replicate the API endpoint exactly by allowing to add/remove all three kinds of targets with only one method. This would be more flexible, intuitive and idiomatic. The old `Add`/`Remove` targets could be deprecated, so this change wouldn't be breaking.

**Comment by apricote** [comment]
# specialized vs general methods

I think having different structs as the opts is actually easier for the user.

All three options take different parameters, so cramming them into a single Opts struct requires additional documentation and understanding.

```go
type AddTargetOpts {
  // Only one of these may be set. How do we handle if the user sets multiple?
  Server   *Server
  Selector *string
  IP       *net.IP

  // Only valid if Server or Selector was set. What do we do if IP was set? Ignore or error?
  UsePrivateIP *bool
}
```

Though a general method would match the API more closely.

# Opts

Using `Opts` is always nicer, as we can amend the opts if new fields are added to the API.

Historically it looks like `hcloud-go` only used Opts when the endpoint actually had more than one parameter, and otherwise put the one parameter directly in the function arguments.

Happy to change this in v3.
